version: 0.1.0-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\whereami-rs

install:
  - curl -L https://static.rust-lang.org/dist/rust-beta-x86_64-pc-windows-gnu.msi -oC:\rust-beta-x86_64-pc-windows-gnu.msi
  - start /w msiexec /qn /quiet /passive /a C:\rust-beta-x86_64-pc-windows-gnu.msi TARGETDIR="C:\Program Files"
  -
  - set PATH=%PATH%;C:\Program Files\Rust\bin;C:\
  - set LIBRARY_PATH=C:\

build: off
build_script:
  - cargo build --verbose

test: off
test_script:
  - cargo test --verbose

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
